### ISSUE TITLE
Cannot run wpt_batch.py without options

### ISSUE THREAD

**Issue by jalanb** [WPO-Foundation/webpagetest#803]
According to the documentation (at https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-batch-processing-command-line-tool#TOC-The-batch-test-with-all-default-setup-) the script `wpt_batch.py` should run without any options. Trying that produces the following traceback:
```$ ./wpt_batch.py
Traceback (most recent call last):
  File "./wpt_batch.py", line 206, in <module>
    main()
  File "./wpt_batch.py", line 203, in main
    RunBatch(options)
  File "./wpt_batch.py", line 103, in RunBatch
    options.server)
  File "/Users/jab/src/git/hub/webpagetest/batchtool/wpt_batch_lib.py", line 71, in SubmitBatch
    response = __LoadEntity(request, urlopen)
  File "/Users/jab/src/git/hub/webpagetest/batchtool/wpt_batch_lib.py", line 31, in __LoadEntity
    response = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 346, in open_http
    h.endheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 914, in endheaders
    self._send_output()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 786, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 745, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 726, in connect
    self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 547, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
```

Debugging into the traceback suggests that the problem arises from [line 162](https://github.com/WPO-Foundation/webpagetest/blob/master/batchtool/wpt_batch.py#L162) where the default server is set to `http://your_wpt_site/`

Same traceback is seen for the other examples on the documentation page

I suppose this is more a documentation error than a code error.

In looking through the file for further help I found a URL for a wiki on [line 8](https://github.com/WPO-Foundation/webpagetest/blob/master/batchtool/wpt_batch.py#L8). This URL seems to be obsolete

**Comment by pmeenan** [comment]
It's a documentation issue and the default options need to be modified in the script if you want to use it.  At a minimum you need to provide the WebPageTest server you are going to run against and the API key to use (if your server is configured with keys).
